services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    networks:
      searxng:
        aliases:
          - "searxng-nginx"
    ports:
          - "0.0.0.0:8082:8082"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - searxng
    command: nginx -g 'daemon off;'
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    labels:
      - homepage.description=SearXNG
      - homepage.group=Self-Hosted
      - homepage.href=http://192.168.1.11:8082/
      - homepage.icon=searxng.png
      - homepage.name=SearXNG
  searxng:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    networks:
      searxng:
        aliases:
          - "searxng-service"
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/  # Changed to http
      - UWSGI_WORKERS=${SEARXNG_UWSGI_WORKERS:-4}
      - UWSGI_THREADS=${SEARXNG_UWSGI_THREADS:-4}
      - REDIS_URL=redis://searxng-redis:6379/0  # Added Redis connection
    depends_on:
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    # Modified healthcheck to use wget which is available in the container
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8080/healthz"]
      interval: 1m30s
      timeout: 10s
      start_period: 2m
      retries: 3
networks:
  searxng:
