# This configuration file updates the default configuration file
# See https://github.com/searxng/searxng/blob/master/searx/limiter.toml

[botdetection.ip_limit]
# activate link_token method in the ip_limit method
link_token = true

[botdetection.ip_lists]
# No IP is explicitly blocked at this stage
block_ip          = []
# No IP is exempted—every IP is subject to rate limits
pass_ip           = []
# Disable the built-in SearXNG org passlist (not needed here)
pass_searxng_org  = false